config/routes.rb
Rails.application.routes.draw do
  get 'vehicles/index'

  namespace :api do
    namespace :v1 do
      post "/gps" => "locations#create"
    end
  end

  get "/show/" => "vehicles#show", :as => "vehicle_show"
  get "/show_waypoints/:id" => "vehicles#show_waypoints", :as => "vehicle_waypoints"
  root 'vehicles#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :waypoints, class_name: 'Waypoint'
  has_many :vehicles, through: :waypoints
  validates :latitude, presence: true
  validates :longitude, presence: true
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_many :waypoints, class_name: 'Waypoint'
  has_many :locations, through: :waypoints
  validates :vehicle_identifier, presence: true, uniqueness: true
end

app/models/waypoint.rb
class Waypoint < ActiveRecord::Base
  belongs_to :location
  belongs_to :vehicle
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  respond_to :json
end

app/controllers/api/v1/locations_controller.rb
class Api::V1::LocationsController < Api::V1::BaseController
  before_action :catch_vehicle, only: [:create]

  def create
    # Se guarda la coordenada y la relacion en la tabla de enlace, luego con el proceso asincrono (delay) se guarda el dato adicional
    # esto inserta un registro en la tabla delayed_jobs, el cual se ejecutara
    # al colocar el siguiente comando en la consola rake jobs:work
    sent_at = params[:sent_at].present? ? params[:sent_at] : DateTime.now
    @location = @vehicle.locations.create(locations_params)
    @location.save
    @waypoint = Waypoint.find_by(vehicle_id: @vehicle.id, location_id: @location.id)
    @waypoint.delay.update(sent_at: sent_at)
    if @location.save
      render status: 200, json: { message: " Guardado con exito! " }
    else
      render status: 404, json: { message: " No se ha guardado! ", errors: @location.errors.messages }
    end
  end

  private

    def locations_params
      params.require(:location).permit!
    end

    def catch_vehicle
      if params[:vehicle_identifier]
        @vehicle = Vehicle.find_or_create_by(vehicle_identifier: params[:vehicle_identifier])
      else
        render status: 404, json: { :message => " Debe ingresar un vehiculo" }
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show_waypoints]
  def index
    @vehicles = Vehicle.all
  end

  def show
    # Ultima ubicacion por cada vehiculo
    @vehicles = Vehicle.all
    @vehicles_last_location = @vehicles.map{ |v| v.locations.last }.compact
    respond_to do |format|
      format.html
      format.json { render json: { locations: @vehicles_last_location } }
    end
  end

  def show_waypoints
  end

  private
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beetrack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "application" %>
  <script src="//maps.google.com/maps/api/js?key=AIzaSyBZGgxb_0d9HeE_QXOzrM6R0Kr0cCMlk5k"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/vehicles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9"><h1>Vehicle List </h1></div>
    <div class="col-md-3"><%= link_to "Show vehicles' recent location (Map)", vehicle_show_path, class: "btn btn-success pull-right btn-back" %></div>
  </div>
  <hr>
  <br>
  <table class="table table-hover">
    <tr>
      <th>#</th>
      <th>Vehicle identifier</th>
      <th>All Historical coordinates for vehicle</th>
    </tr>

    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.id %></td>
        <td><%= vehicle.vehicle_identifier %></td>
        <td><%= link_to "Historical waypoints", vehicle_waypoints_path(vehicle.id), class: "btn btn-info" %></td>
      </tr>
    <% end %>

  </table>
</div>

app/views/vehicles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9"><h1>Vehicles' most recent coordinate</h1></div>
    <div class="col-md-3"><%= link_to "Back", root_path, class: "btn btn-info pull-right btn-back" %></div>
  </div>
  <hr>
  <br>

  <div id="map" class="map-border"></div>
</div>

app/views/vehicles/show_waypoints.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9"><h1>Vehicle #<%= @vehicle.id  %> historical waypoints </h1></div>
    <div class="col-md-3"><%= link_to "Back", root_path, class: "btn btn-info pull-right btn-back" %></div>
  </div>
  <hr>
  <br>
  <table class="table table-hover">
    <tr>
      <th>Location #</th>
      <th>Latitude</th>
      <th>Longitude</th>
    </tr>

    <% @vehicle.locations.each_with_index do |locations, i| %>
      <% index = i + 1 %>
      <tr>
        <td><%= index %></td>
        <td><%= locations.latitude %></td>
        <td><%= locations.longitude %></td>
      </tr>
    <% end %>

  </table>
</div>